version: "3"
services:
  filestash:
    container_name: filestash
    #image: docker-mirror.kubarcloud.com/machines/filestash
    image: machines/filestash
    volumes:
      - ./data/filestash:/app/data
    environment:
    - APPLICATION_URL=file.9craft.ir
    ports:
    - 8334:8334
    dns:
      - 192.168.1.2
    networks:
      - backend
      - minecraft
    restart: always

  ftpd_server:
    #build: .
    #image: hub.hamdocker.ir/stilliard/pure-ftpd
    image: testing:vvv
    container_name: pure-ftpd
    environment:
    - FTP_MAX_CLIENTS=100
    - FTP_MAX_CONNECTIONS=100
    - FTP_USER_UID=1001
    - FTP_USER_GID=1001
    - FTP_PASSIVE_PORTS=4200:4300
    ports:
      - 127.0.0.1:20:20
      - 127.0.0.1:21:21
      - 4200-4300:4200-4300
    networks:
      - backend
    volumes:
      - /opt/user_data:/opt
      - ftp-data:/etc/pure-ftpd/
      - ./new_user.sh:/bin/new_user.sh
      - ./del_user.sh:/bin/del_user.sh
    restart: always


  prometheus:
    image: hub.hamdocker.ir/prom/prometheus:v2.28.1
    container_name: prometheus
    environment:
      TZ: Asia/Tehran
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus/prometheus:/prometheus
      - ./configs/prometheus/rules.yml:/etc/prometheus/rules.yml
      - /etc/hosts:/etc/hosts
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=60d
    user: root
    ports:
      - 127.0.0.1:9090:9090
    dns:
      - 192.168.1.2
    networks:
      - backend
      - minecraft
    restart: always


  alertmanager:
    image: hub.hamdocker.ir/prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./configs/prometheus/alertmanager.yml:/etc/alertmanager/config.yml
      - /etc/hosts:/etc/hosts
    command:
      - '--config.file=/etc/alertmanager/config.yml'

  grafana:
    image: hub.hamdocker.ir/grafana/grafana:8.0.6
    container_name: grafana
    hostname: grafana
    user: root
    environment:
      TZ: Asia/Tehran
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 0.0.0.0:3000:3000
    networks:
      - backend
    restart: always


  nginx:
    image: hub.hamdocker.ir/nginx:latest
    container_name: nginx
    ports:
      - 185.181.180.153:80:80
      - 185.181.180.153:443:443
      #- 127.0.0.1:80:80
      #- 127.0.0.1:443:443

    volumes:
      - ../frontend-dists/dist:/usr/share/nginx/html
      - ./configs/nginx/servers.conf:/etc/nginx/conf.d/default.conf
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/seyed/front:/front
      - /home/seyed/front/build2:/front2

    networks:
      - backend
      - radio
    environment:
      TZ: Asia/Tehran
      PUID: 1000
      PGID: 1000
    cap_add:
      - SYS_NICE
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    restart: always


  porty_nginx:
    image: hub.hamdocker.ir/nginx:latest
    container_name: porty_nginx
    ports:
      - "45000-45010:45000-45010"
    volumes:
      - ./configs/nginx/porty_nginx_stream.conf:/etc/nginx/stream.d/s.conf
      - ./configs/nginx/porty_nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
      - radio
      - minecraft
    environment:
      TZ: Asia/Tehran
      PUID: 1000
      PGID: 1000
    dns:
      - 192.168.1.3
    cap_add:
      - SYS_NICE
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    restart: always


  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  dns:
    image: docker-mirror.kubarcloud.com/teddysun/xray
    container_name: dns
    restart: always
    networks:
      - minecraft
    volumes:
      - ./configs/dns.json:/etc/xray/config.json
    ports:
      - "192.168.1.2:53:53/tcp"
      - "192.168.1.2:53:53/udp"
    dns:
      - 192.168.1.3
  registry:
    image: docker-mirror.kubarcloud.com/registry:2
    container_name: my-registry-daemon
    restart: always
    ports:
      - "192.168.1.2:5050:5000"
    volumes:
      - registry-data:/var/lib/registry

  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: hub.kubarcloud.com/technitium/dns-server:latest
    ports:
      - "127.0.0.1:5380:5380/tcp" #DNS web console (HTTP)
      - "185.181.180.153:53:53/udp" #DNS service
      - "185.181.180.153:53:53/tcp" #DNS service
    environment:
      - DNS_SERVER_DOMAIN=dns-server #The primary domain name used by this DNS Server to identify itself.
      - DNS_SERVER_ADMIN_PASSWORD=hardP@ssw0rd #DNS web console admin user password.
      - DNS_SERVER_WEB_SERVICE_LOCAL_ADDRESSES=172.17.0.1,127.0.0.1 #Comma separated list of network interface IP addresses that you want the web service to listen on for requests. The "172.17.0.1" address is the built-in Docker bridge. The "[::]" is the default value if not specified. Note! This must be used only with "host" network mode.
      # - DNS_SERVER_WEB_SERVICE_HTTP_PORT=5380 #The TCP port number for the DNS web console over HTTP protocol.
      # - DNS_SERVER_WEB_SERVICE_HTTPS_PORT=53443 #The TCP port number for the DNS web console over HTTPS protocol.
      # - DNS_SERVER_WEB_SERVICE_ENABLE_HTTPS=false #Enables HTTPS for the DNS web console.
      # - DNS_SERVER_OPTIONAL_PROTOCOL_DNS_OVER_HTTP=false #Enables DNS server optional protocol DNS-over-HTTP on TCP port 8053 to be used with a TLS terminating reverse proxy like nginx.
      # - DNS_SERVER_RECURSION=AllowOnlyForPrivateNetworks #Recursion options: Allow, Deny, AllowOnlyForPrivateNetworks, UseSpecifiedNetworkACL.
      # - DNS_SERVER_RECURSION_NETWORK_ACL=192.168.10.0/24, !192.168.10.2 #Comma separated list of IP addresses or network addresses to allow access. Add ! character at the start to deny access, e.g. !192.168.10.0/24 will deny entire subnet. The ACL is processed in the same order its listed. If no networks match, the default policy is to deny all except loopback. Valid only for `UseSpecifiedNetworkACL` recursion option.
      # - DNS_SERVER_RECURSION_DENIED_NETWORKS=1.1.1.0/24 #Comma separated list of IP addresses or network addresses to deny recursion. Valid only for `UseSpecifiedNetworkACL` recursion option. This option is obsolete and DNS_SERVER_RECURSION_NETWORK_ACL should be used instead.
      # - DNS_SERVER_RECURSION_ALLOWED_NETWORKS=127.0.0.1, 192.168.1.0/24 #Comma separated list of IP addresses or network addresses to allow recursion. Valid only for `UseSpecifiedNetworkACL` recursion option.  This option is obsolete and DNS_SERVER_RECURSION_NETWORK_ACL should be used instead.
      # - DNS_SERVER_ENABLE_BLOCKING=false #Sets the DNS server to block domain names using Blocked Zone and Block List Zone.
      # - DNS_SERVER_ALLOW_TXT_BLOCKING_REPORT=false #Specifies if the DNS Server should respond with TXT records containing a blocked domain report for TXT type requests.
      # - DNS_SERVER_BLOCK_LIST_URLS= #A comma separated list of block list URLs.
      # - DNS_SERVER_FORWARDERS=1.1.1.1, 8.8.8.8 #Comma separated list of forwarder addresses.
      # - DNS_SERVER_FORWARDER_PROTOCOL=Tcp #Forwarder protocol options: Udp, Tcp, Tls, Https, HttpsJson.
      # - DNS_SERVER_LOG_USING_LOCAL_TIME=true #Enable this option to use local time instead of UTC for logging.
    volumes:
      - ./data/dns/dns:/etc/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000

volumes:
  ftp-data:
  registry-data:

networks:
  minecraft:
    external:
      name: minecraft
  backend:
    external:
      name: backend
  radio:
    external:
      name: radio
