
alerting:
  alertmanagers:
  - scheme: https
    static_configs:
    - targets:
       - "alert.kubarcloud.com"
rule_files:
  - "rules.yml"
scrape_configs:
- job_name: mc servers
  http_sd_configs:
  - url: http://web:5000/prometheus/targets/1c5d76b2e8a94fcb02301f682f348d0d.json
- job_name: phyiscal servers
  metrics_path: /metrics
  scrape_interval: 15s
  scheme: http
  static_configs:
    - targets:
      - 172.17.0.1:9100
      - 192.168.1.3:9100

