scrape_configs:
- job_name: mc servers
  http_sd_configs:
  - url: http://192.168.1.12:8000/index.json
- job_name: phyiscal servers
  metrics_path: /metrics
  scrape_interval: 15s
  scheme: http
  static_configs:
    - targets:
      - 192.168.1.12:9100
      labels:
        hostname: ser-physical-01
        __metrics_path__: /metrics

