{
 "title": "Minecraft",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "username", "label": "Username", "query": { "query": "label_values(up{}, username)" } },
   {
    "name": "world_name",
    "label": "World",
    "query": {
     "query": "label_values(up{username=~\"$username\"}, world_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Players",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_players_total{username=\"$username\", world_name=\"$world_name\"}",
     "legendFormat": "Unique"
    },
    {
     "expr": "sum(mc_players_online_total{server_name=~\"$server_name\"}) by (world)",
     "legendFormat": "Online ({{world}})"
    }
   ]
  },
  {
   "title": "Players Online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mc_players_online_total{username=\"$username\", world_name=\"$world_name\"})"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mc_jvm_memory{type='allocated',username=\"$username\", world_name=\"$world_name\"} - scalar(mc_jvm_memory{type='free', username=\"$username\", world_name=\"$world_name\"})"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mc_tps{username=\"$username\", world_name=\"$world_name\"}"
    }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_loaded_chunks_total{username=\"$username\", world_name=\"$world_name\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mc_jvm_memory{type='max', username=\"$username\", world_name=\"$world_name\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "mc_jvm_memory{type='allocated', server_name=~\"$server_name\"} - scalar(mc_jvm_memory{type='free', server_name=~\"$server_name\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (mc_entities_total{username=\"$username\", world_name=\"$world_name\"}) by (world)",
     "legendFormat": "{{world}}_total"
    }
   ]
  },
  {
   "title": "Tickrate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mc_tps{username=\"$username\", world_name=\"$world_name\"}",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Villagers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (mc_villagers_total{username=\"$username\", world_name=\"$world_name\"}) by (world, level, profession)",
     "legendFormat": "{{world}}:  {{profession}}  (lv{{level}})"
    }
   ]
  }
 ]
}